Repository Cloud-CV/EvalAI, pull requests merged in 2018-09, with the labels that each got.

#1801 Submission Worker: Add exception handling if there is a syntax error
  scripts/workers/submission_worker.py
Labels: backend, bug, critical, easy_to_fix

#1804 Add Feature to view Private leaderboard
  apps/challenges/views.py
  apps/jobs/views.py
  frontend/src/js/controllers/challengeCtrl.js
  frontend/src/views/web/challenge/leaderboard.html
  tests/unit/challenges/test_views.py
Labels: new-feature, priority-high

#1775 Add Forum Link in Header
  frontend/src/js/controllers/challengeCtrl.js
  frontend/src/views/web/challenge/challenge-page.html
  frontend/src/views/web/partials/main-header.html
  frontend/src/views/web/partials/sim-header.html
Labels: can-be-merged, frontend, new-feature, priority-high

#1776 Add field to store forum url along with migrations
  apps/challenges/migrations/0037_add_field_to_store_forum_url.py
  apps/challenges/models.py
  apps/challenges/serializers.py
  tests/unit/challenges/test_views.py
  tests/unit/participants/test_views.py
Labels: can-be-merged, new-feature, priority-high

#1811 Deployment: Add files for docker based deployment
  .dockerignore
  docker-compose-production.yml
  docker-compose-staging.yml
  docker-compose.yml
  docker/prod/nodejs/Dockerfile_staging
  frontend/src/js/config.json
  settings/staging.py
Labels: can-be-merged

#1790 Fix # 1787: Adds created_at as a read-only field in django admin panel
  apps/challenges/admin.py
Labels: can-be-merged
