Repository Cloud-CV/EvalAI, pull requests merged in 2018-03, with the labels that each got.

#1555 Add support to share challenge phase leaderboard
  frontend/src/js/controllers/challengeCtrl.js
  frontend/src/js/route-config/route-config.js
  frontend/src/views/web/challenge/leaderboard.html
Labels: priority-high

#1506 Fix #1080: Add functionality to disable challenge
  apps/challenges/views.py
  tests/unit/challenges/test_views.py
Labels: backend

#1550 Add feature to notify Users about new challenge via email.
  apps/accounts/static/accounts/css/main.css
  apps/web/templates/notification_email.html
  apps/web/templates/notification_email_conformation.html
  apps/web/templates/notification_email_data.html
  apps/web/urls.py
  apps/web/views.py
  tests/unit/web/test_views.py
Labels: priority-high

#1559 Modify Leaderboard UI to show the details prettier
  bower.json
  frontend/app.scripts.json
  frontend/src/css/modules/base.scss
  frontend/src/js/app.js
  frontend/src/js/controllers/challengeCtrl.js
  frontend/src/js/controllers/featuredChallengeCtrl.js
  frontend/src/views/web/challenge/leaderboard.html
  frontend/src/views/web/featured-challenge/leaderboard.html
Labels: can-be-merged, priority-high

#1484 Fix #1080: Add functionality to disable challenge
  frontend/src/js/controllers/challengeCtrl.js
  frontend/src/views/web/challenge/challenge-page.html
  frontend/src/views/web/challenge/delete-challenge/delete-challenge.html
Labels: can-be-merged, frontend

#1577 Fix bug in Last Submission date time analysis API
  apps/analytics/views.py
  tests/unit/analytics/test_views.py
Labels: bug, can-be-merged, priority-high

#1579 Fix bug in create challenge using zip file
  apps/challenges/views.py
Labels: bug, can-be-merged, priority-high

#1585 Modify challenge evaluation and phase page
  frontend/src/views/web/challenge/evaluation.html
  frontend/src/views/web/challenge/phases.html
  frontend/src/views/web/challenge/submission.html
Labels: can-be-merged, enhancement, frontend

#1583 Fix bug in showing total submissions done to a challenge phase
  frontend/src/js/controllers/challengeCtrl.js
Labels: can-be-merged, frontend, priority-high

#1587 Fix display for showing remaining submissions.
  frontend/src/css/modules/base.scss
  frontend/src/views/web/challenge/submission.html
Labels: can-be-merged, priority-high

#1538 Add support for changing Participant Team Name
  frontend/src/js/controllers/teamsCtrl.js
  frontend/src/views/web/teams.html
Labels: priority-high

#1355 Fix #630: Add backend for resend E-mail feature.
  apps/accounts/throttles.py
  apps/accounts/urls.py
  apps/accounts/views.py
  requirements/common.txt
  settings/common.py
  settings/dev.sample.py
  tests/unit/accounts/test_throttles.py
Labels: backend

#1354 Fix #630: Add frontend for resend E-mail feature.
  frontend/src/js/controllers/permissionCtrl.js
  frontend/src/views/web/permission-denied.html
Labels: frontend
