Repository Cloud-CV/EvalAI, pull requests merged in 2018-07, with the labels that each got.

#1739 Added functionality to display explicit error
  frontend/src/js/controllers/challengeHostTeamsCtrl.js
  frontend/src/js/controllers/teamsCtrl.js
Labels: can-be-merged

#1744 Restrict API to give results for only participant team
  apps/analytics/serializers.py
  apps/analytics/urls.py
  apps/analytics/views.py
  frontend/src/js/controllers/challengeCtrl.js
  tests/unit/analytics/test_views.py
Labels: critical, priority-high, review-required

#1750 Add migration file for unique random name of challenge logo
  apps/challenges/migrations/0036_Add_unique_random_name_to_challenge_logo.py
Labels: bug, critical, review-required

#1729 Add blank field for optional models
  apps/jobs/migrations/0010_Add_blank_in_submission_metadata.py
  apps/jobs/models.py
  apps/participants/migrations/0010_Add_blank_in_team_URL.py
  apps/participants/models.py
Labels: can-be-merged, priority-high

#1745 Add API for challenge phase analytics
  apps/analytics/serializers.py
  apps/analytics/urls.py
  apps/analytics/views.py
  frontend/src/js/controllers/analyticsCtrl.js
  tests/unit/analytics/test_views.py
Labels: critical, dependent, priority-high

#1748 Modify condition for showing remaining submissions
  apps/jobs/views.py
  tests/unit/jobs/test_views.py
Labels: bug, critical, review-required

#1730 Add Team URL in update participant team dialog
  frontend/src/js/controllers/challengeCtrl.js
  frontend/src/js/controllers/teamsCtrl.js
  frontend/src/views/web/challenge/participate.html
  frontend/src/views/web/edit_teams.html
  frontend/src/views/web/teams.html
Labels: can-be-merged, dependent, priority-high
