Repository Cloud-CV/EvalAI, pull requests merged in 2019-12, with the labels that each got.

#2495 Open external links in new tabs
  frontend/src/views/web/about-us.html
  frontend/src/views/web/get-involved.html
Labels: can-be-merged

#2493 Add check to stop sending invite to participant team if user's email is in blocked email domains
  apps/challenges/utils.py
  apps/challenges/views.py
  apps/participants/views.py
  tests/unit/participants/test_views.py
Labels: priority-high

#2514 Fix GitHub Case
  docs/source/faq(developers).md
  frontend/src/views/web/get-involved.html
  frontend/src/views/web/profile.html
  frontend/src/views/web/update-profile.html
Labels: can-be-merged

#2359 Mocking AWS ECR requests for Development Environment
  apps/base/utils.py
  apps/challenges/utils.py
  apps/challenges/views.py
  requirements/common.txt
  requirements/dev.txt
  tests/unit/challenges/test_urls.py
  tests/unit/challenges/test_views.py
Labels: code-upload, priority-high

#2410 Script to make EKS Kube Config for RL Worker
  scripts/workers/rl_kube_warmup.sh
Labels: code-upload

#2415 RL Worker and required util to interact with API
  scripts/workers/rl_submission_worker.py
  scripts/workers/worker_util.py
Labels: code-upload

#2512 Fix #1705: Add support for editing the challenge start end end date
  frontend/src/js/controllers/challengeCtrl.js
  frontend/src/views/web/challenge/challenge-page.html
  frontend/src/views/web/challenge/edit-challenge/edit-challenge-date.html
Labels: can-be-merged

#2429 Fix Endpoint to delete message from Queue
  apps/jobs/urls.py
  apps/jobs/views.py
  scripts/workers/remote_submission_worker.py
  tests/unit/remoteworker/test_remote_worker.py
Labels: code-upload

#2392 Adding Environment URL field in Phase model
  apps/challenges/migrations/0058_adding_environment_url_for_rl_challenges.py
  apps/challenges/models.py
  apps/challenges/urls.py
  apps/challenges/views.py
Labels: code-upload

#2376 RL Challenge Submission API
  apps/jobs/admin.py
  apps/jobs/sender.py
  apps/jobs/tasks.py
  apps/jobs/views.py
  tests/unit/jobs/test_views.py
Labels: code-upload

#2558 API fixes for RL submission worker
  apps/base/utils.py
  apps/jobs/admin.py
  apps/jobs/views.py
  scripts/workers/worker_util.py
Labels: priority-high
