Repository Cloud-CV/EvalAI, pull requests merged in 2019-01, with the labels that each got.

#1942 Add new link to postgreshelp
  README.md
Labels: can-be-merged

#1940 Fix #1938: Handle YAML in Temporary Directory in Zip File
  apps/challenges/views.py
Labels: can-be-merged

#1968 Fix #1964 View stars without login
  apps/challenges/views.py
  frontend/src/views/web/challenge/challenge-page.html
Labels: can-be-merged

#1901 Change maximum character limit
  frontend/src/views/web/update-profile.html
Labels: can-be-merged

#1925 Fixes aligment issue of edit challenge title dialog box of my hosted challenges page
  frontend/src/views/web/challenge/edit-challenge/edit-challenge-title.html
Labels: can-be-merged

#2013 Fix minor bug in get_remaining_submissions_api
  apps/jobs/views.py
  tests/unit/jobs/test_views.py
Labels: can-be-merged

#2031 Fix bug in Leaderboard Data Admin
  apps/challenges/admin.py
Labels: bug, critical, priority-high

#1985 [WIP] Fix #1929 Two Loaders working at same time
  frontend/src/views/web/challenge/participate.html
Labels: can-be-merged

#1890 Edit challenge name button disbaled when no changes are made
  frontend/src/views/web/challenge/edit-challenge/edit-challenge-title.html
Labels: can-be-merged

#1989 Fix #1893 Add support for Editing Host Team name
  apps/hosts/migrations/Add_blank_in_host_team_URL.py
  apps/hosts/models.py
  frontend/src/js/controllers/challengeHostTeamsCtrl.js
  frontend/src/views/web/challenge-host-teams.html
  frontend/src/views/web/edit-host-teams.html
Labels: can-be-merged

#2026 Fix #2019: Changed the submission visibility to public by Default
  apps/jobs/migrations/0011_Change_submission_visibility_default_to_public.py
  apps/jobs/models.py
Labels: can-be-merged

#2029 Fix issue for redirecting to the next state after login
  frontend/src/js/route-config/route-config.js
Labels: can-be-merged

#1999 Fix #1996: Django Updated to 1.11.18
  requirements/common.txt
Labels: can-be-merged

#2043 Change API to display featured challenges on landing page
  frontend/src/js/controllers/mainCtrl.js
Labels: priority-high

#2037 Fix #2036: Correcting Typos
  frontend/src/views/web/challenge/participate.html
  frontend/src/views/web/challenge/submission.html
  frontend/src/views/web/featured-challenge/participate.html
Labels: can-be-merged

#1905 Fix : Update profile and Token shown when viewed in <980px
  frontend/src/views/web/auth/get-token.html
  frontend/src/views/web/profile.html
  frontend/src/views/web/update-profile.html
Labels: can-be-merged
