Repository Cloud-CV/EvalAI, pull requests merged in 2019-03, with the labels that each got.

#2156 Display consistent public leaderboard for host and participant
  apps/jobs/views.py
  tests/unit/jobs/test_views.py
Labels: priority-high

#2140 Fix #2103: Redirect users to Profile section on less than medium screen
  frontend/src/views/web/partials/dyn-header.html
  frontend/src/views/web/partials/sim-header.html
Labels: can-be-merged

#2128 Fix #2127: Update the Django version
  requirements/common.txt
Labels: can-be-merged

#2132 [WIP]Add challenge slug field in Seed script
  scripts/seed.py
Labels: can-be-merged

#2136 Fix #2134 Removed duplicates of self.challenge_phase.save()
  tests/unit/jobs/test_views.py
Labels: can-be-merged

#2150 Fix input field height
  frontend/src/css/modules/auth.scss
Labels: can-be-merged

#1937 [WIP] Fix #1936 : Test for Admin Action
  tests/unit/jobs/test_admin.py
Labels: can-be-merged

#2180 Fix EvalAI vertical alignment
  frontend/src/css/modules/main-header.scss
  frontend/src/views/web/partials/main-header.html
  frontend/src/views/web/partials/sim-header.html
Labels: can-be-merged

#2062 Fix #2061: Update the Documentation for Monthly Submission Limit Per Team for Challenge Creation
  docs/source/challenge_creation.md
Labels: can-be-merged

#2196 Fix #2194: Added Total Participants in Analysis Page in a Challenge
  frontend/src/css/modules/base.scss
  frontend/src/js/controllers/analyticsCtrl.js
  frontend/src/views/web/analytics/host-analytics.html
Labels: can-be-merged

#1927 Fix #1923: Tests for Update Submission Data
  tests/unit/jobs/test_views.py
Labels: can-be-merged, priority-high

#2191 Allow certain email ids to participate in a phase
  apps/challenges/migrations/0044_add_field_to_allow_email_ids_in_challenge_phase.py
  apps/challenges/models.py
  apps/jobs/views.py
  tests/unit/jobs/test_views.py
Labels: can-be-merged, priority-high

#2182 Fix #2179: Add status in contact messages
  apps/web/admin.py
  apps/web/migrations/0006_add_status_field_in_contact_model.py
  apps/web/models.py
Labels: can-be-merged

#2056 Fix #2048: Added Leaderboard Description
  apps/challenges/migrations/0045_Add_leaderboard_description_field_in_challenge.py
  apps/challenges/models.py
  apps/challenges/serializers.py
  frontend/src/views/web/challenge/leaderboard.html
  frontend/src/views/web/featured-challenge/leaderboard.html
  tests/unit/challenges/test_views.py
  tests/unit/participants/test_views.py
Labels: priority-high

#2201 Fix #2189: Display error on UI while creating challenge
  apps/challenges/views.py
  frontend/src/css/modules/challenge-create.scss
  frontend/src/js/controllers/challengeCreate.js
  frontend/src/views/web/challenge-create.html
Labels: can-be-merged, priority-high

#2129 Add feature to limit the concurrent submission message processing from SQS
  apps/challenges/migrations/0046_add_max_concurrent_submission_evaluation_in_challenge.py
  apps/challenges/models.py
  apps/jobs/urls.py
  apps/jobs/views.py
  scripts/workers/submission_worker.py
Labels: priority-high

#2199 Fix pagination logic in frontend pages
  frontend/src/js/controllers/challengeCtrl.js
  frontend/src/js/controllers/challengeHostTeamsCtrl.js
  frontend/src/js/controllers/teamsCtrl.js
  frontend/src/views/web/challenge-host-teams.html
  frontend/src/views/web/challenge/my-challenge-all-submission.html
  frontend/src/views/web/challenge/my-submission.html
  frontend/src/views/web/teams.html
Labels: priority-high

#2176 Add feature to invite participants in a challenge via email by challenge host
  apps/accounts/serializers.py
  apps/base/utils.py
  apps/challenges/admin.py
  apps/challenges/migrations/0047_add_model_to_invite_user_in_challenge.py
  apps/challenges/models.py
  apps/challenges/serializers.py
  apps/challenges/urls.py
  apps/challenges/views.py
  docker/dev/docker.env
  docker/prod/docker_production.env
  docker/prod/docker_staging.env
  frontend/src/css/main.scss
  frontend/src/css/modules/base.scss
  frontend/src/css/modules/challenge-invitation.scss
  frontend/src/js/controllers/ChallengeInviteCtrl.js
  frontend/src/js/route-config/route-config.js
  frontend/src/views/web/challenge-invite.html
  requirements/common.txt
  settings/common.py
  tests/unit/accounts/test_views.py
Labels: priority-high

#2229 Add aws details of challenge host in challenge
  apps/base/utils.py
  apps/challenges/migrations/0048_add_fields_to_store_host_aws_keys.py
  apps/challenges/models.py
  apps/challenges/utils.py
  apps/challenges/views.py
  apps/participants/utils.py
Labels: priority-high

#2234 Remove docker repository uri from participant team
  apps/base/utils.py
  apps/challenges/utils.py
  apps/challenges/views.py
  apps/participants/admin.py
  apps/participants/migrations/0012_remove_docker_repository_uri_from_team.py
  apps/participants/models.py
  apps/participants/serializers.py
  tests/unit/participants/test_views.py
Labels: priority-high

#2239 Removes database dependency from submission worker
  apps/base/utils.py
  apps/challenges/urls.py
  apps/challenges/views.py
  apps/jobs/sender.py
  apps/jobs/urls.py
  apps/jobs/views.py
  docker-compose-production.yml
  docker-compose-staging.yml
  docker-compose.yml
  docker/dev/docker.env
  scripts/deployment/deploy.sh
  scripts/workers/remote_submission_worker.py
  scripts/workers/submission_worker.py
  tests/unit/challenges/test_views.py
Labels: priority-high

#2236 Fix Typo
  frontend/src/js/controllers/challengeHostTeamsCtrl.js
Labels: can-be-merged

#2195 Submissions: Add API to get signed URL of a file in S3 bucket
  apps/jobs/urls.py
  apps/jobs/views.py
  apps/participants/utils.py
  frontend/src/js/controllers/SubmissionFilesCtrl.js
  frontend/src/js/route-config/route-config.js
Labels: priority-high
