Repository Cloud-CV/EvalAI, pull requests merged in 2019-05, with the labels that each got.

#2049 Fix #2046: Center align the footer of dashboard when viewed below med…
  frontend/src/views/web/partials/dashboard-footer.html
Labels: can-be-merged

#1998 Fix #1997: Add settings files to coverage exclusion list
  .coveragerc
Labels: can-be-merged

#2073 Fix #2060: Fix notification for unverified users in profile section
  frontend/src/js/controllers/profileCtrl.js
Labels: can-be-merged

#2069 Fix #2068 :Make evaluation criteria persistent when eval script dialog is open/closed
  frontend/src/js/controllers/challengeCtrl.js
Labels: can-be-merged

#2050 Fix #2047: Add notification for changing submission visibility to public/private
  frontend/src/js/controllers/challengeCtrl.js
Labels: can-be-merged

#2071 Fix #1740 : Bug fix in API for fetching challenge phase details
  apps/challenges/views.py
  tests/unit/challenges/test_views.py
Labels: can-be-merged

#2002 Fix #2001: Disable submit button if any of the submission limit is exhausted
  frontend/src/js/controllers/challengeCtrl.js
  frontend/src/views/web/challenge/submission.html
Labels: needs-more-work

#2072 Fix #1892: Feature to show/hide password on login, signup, change & reset password pages
  frontend/src/js/controllers/authCtrl.js
  frontend/src/js/controllers/changePwdCtrl.js
  frontend/src/views/web/auth/login.html
  frontend/src/views/web/auth/reset-password-confirm.html
  frontend/src/views/web/auth/signup.html
  frontend/src/views/web/change-password.html
Labels: can-be-merged

#2298 Frontend+Backend: Add feature to download a list of participant teams participating in a challenge
  apps/analytics/urls.py
  apps/analytics/views.py
  apps/participants/serializers.py
  frontend/src/css/modules/base.scss
  frontend/src/js/controllers/analyticsCtrl.js
  frontend/src/views/web/analytics/host-analytics.html
  tests/unit/analytics/test_urls.py
  tests/unit/analytics/test_views.py
Labels: priority-high

#2283 Fix #2181: Add feature for storing/displaying error bars on leaderboard
  apps/challenges/migrations/0052_add_error_bar.py
  apps/challenges/models.py
  apps/jobs/views.py
  frontend/src/views/web/challenge/leaderboard.html
  frontend/src/views/web/featured-challenge/leaderboard.html
  scripts/workers/submission_worker.py
  tests/unit/jobs/test_views.py
Labels: priority-high

#2204 Fixes #2203: Update Python 2 code.
  apps/challenges/views.py
Labels: can-be-merged

#2309 Backend: Add submission Id in the Django admin panel
  apps/jobs/admin.py
Labels: can-be-merged

#1902 Fix #1603: Add feature to export all or specific fields in view all submissions
  apps/challenges/views.py
  frontend/src/css/modules/challenge.scss
  frontend/src/js/controllers/challengeCtrl.js
  frontend/src/views/web/challenge/my-challenge-all-submission.html
  tests/unit/challenges/test_views.py
Labels: can-be-merged

#2174 Fixes #2172: Fix challenge details editing from hosted challenges tab
  frontend/src/js/controllers/hostedChallengeCtrl.js
Labels: can-be-merged

#1991 Fix #1821: Fix downloading auth token in Firefox browser
  frontend/src/js/controllers/profileCtrl.js
Labels: can-be-merged

#2288 Frontend: Configure karma, travis & docker to run unit tests along with writing tests for analytics, auth & create challenge controllers
  .coveragerc
  .travis.yml
  docker/dev/nodejs/Dockerfile
  frontend/src/js/controllers/challengeCreate.js
  frontend/tests/controllers-test/analyticsCtrl.test.js
  frontend/tests/controllers-test/authCtrl.test.js
  frontend/tests/controllers-test/challengeCreate.test.js
  karma.conf.js
  package.json
  pytest.ini
  setup.cfg
Labels: can-be-merged

#2322 Front-end Unit Tests: Dashboard Controller
  frontend/tests/controllers-test/dashCtrl.test.js
Labels: can-be-merged

#2323 Frontend: Add unit tests for change password & our team controller
  frontend/tests/controllers-test/changePwdCtrl.test.js
  frontend/tests/controllers-test/ourteamCtrl.test.js
Labels: can-be-merged

#2321 Frontend: Add unit tests for challenge list controller
  frontend/src/js/controllers/challengeListCtrl.js
  frontend/tests/controllers-test/challengeListCtrl.test.js
Labels: can-be-merged

#2320 Frontend: Add unit tests for contact us & submission files controller
  frontend/tests/controllers-test/SubmissionFilesCtrl.test.js
  frontend/tests/controllers-test/contactUsCtrl.test.js
Labels: can-be-merged

#2315 Frontend: Add unit tests for update profile & permissions controller
  frontend/tests/controllers-test/permissionCtrl.test.js
  frontend/tests/controllers-test/updateProfileCtrl.test.js
Labels: can-be-merged

#2327 Frontend: Add unit tests for featured challenge & my hosted challenges controller
  frontend/tests/controllers-test/featuredChallengeCtrl.test.js
  frontend/tests/controllers-test/hostedChallengeCtrl.test.js
Labels: can-be-merged

#2328 Frontend: Add unit tests for challenge invite & main controller
  frontend/tests/controllers-test/ChallengeInviteCtrl.test.js
  frontend/tests/controllers-test/mainCtrl.test.js
Labels: can-be-merged

#2271 Added Unit Tests for Baseline Submission Leaderboard and Toggle
  tests/unit/jobs/test_views.py
Labels: can-be-merged

#2342 Fix #2341: Update djangorestframework to v3.9.3
  requirements/common.txt
Labels: can-be-merged

#2317 Frontend: Add unit tests for profile & web controller
  frontend/tests/controllers-test/profileCtrl.test.js
  frontend/tests/controllers-test/webCtrl.test.js
Labels: can-be-merged
